### ISSUE TITLE
Can't display curl output

### ISSUE THREAD

**Issue by ayrat555** [riscy/shx-for-emacs#18] opened 2020-03-07 11:16 UTC
It seems `shx` can not parse output from `curl`. The result is not displayed.

**Comment by riscy** [comment] 2020-03-07 16:23
That's strange - can you paste the curl command and/or any messages that pop up?  Did you change `shx-triggers`?  Maybe you can <kbd>M-x toggle-debug-on-error</kbd> and try and see if it gives a traceback due to an error.  It seems to be working at least in a simple couple simple cases:

```bash
~ $ curl https://api.github.com/repos/riscy
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

~ $ curl https://api.github.com/repos/riscy/shx-for-emacs/issues
[
  {
    "url": "https://api.github.com/repos/riscy/shx-for-emacs/issues/18",
    "repository_url": "https://api.github.com/repos/riscy/shx-for-emacs",
    "labels_url": "https://api.github.com/repos/riscy/shx-for-emacs/issues/18/labels{/name}",
```

**Comment by ayrat555** [comment] 2020-03-08 06:00
Hi. Thanks for looking into the issue. Indeed, it works with your example. But it doesn't work with examples of mine.
```
shx-triggers is a variable defined in ‘shx.el’.                                                                      
Its value is                                                                                                         
(("https?://[A-Za-z0-9,./?=&;_-]+[^[:space:].\"'>)]+" . shx--parse-url))   
```
`debug-on-error` didn't show anything

My examples in `shx`:
```
➜  ~ curl -v -H "Content-Type: application/json" --data '{"1":"xyz","password":"xyz"}' http://localhost:4000/api/\
    v1/reorganize                                                                                                     
3012                                                                                                                  
3013<{"1":"xyz","password":"xyz"}' http://localhost:4000/api/v1/reorganize                                            
3014*   Trying 127.0.0.1...                                                                                           
3015* Connected to localhost (127.0.0.1) port 4000 (#0)                                                               
3016> POST /api/v1/reorganize HTTP/1.1                                                                                
3017> Host: localhost:4000                                                                                            
3018> User-Agent: curl/7.47.0                                                                                         
3019> Accept: */*                                                                                                     
3020> Content-Type: application/json                                                                                  
3021> Content-Length: 28                                                                                              
3022>                                                                                                                 
3023* upload completely sent off: 28 out of 28 bytes                                                                  
3024< HTTP/1.1 400 Bad Request                                                                                        
3025< cache-control: max-age=0, private, must-revalidate                                                              
3026< content-length: 115                                                                                             
3027< date: Sun, 08 Mar 2020 05:54:07 GMT                                                                             
3028< server: Cowboy                                                                                                  
3029< x-request-id: Ffo-atDXxTIXSm0AAABE                                                                              
3030<                                                                                                                 
3031* Connection #0 to host localhost left intact                                                                     
3032➜  ~           
```
```

**Comment by ayrat555** [comment] 2020-03-08 08:37
Can this be caused to the fact that I'm making requests to localhost?

**Comment by riscy** [comment] 2020-03-08 21:01
I don't think that should have anything to do with it.  One thing you could do is disable shx-mode (<kbd>M-x shx-mode</kbd>) to ensure that the issue isn't with the built-in Emacs shell.

Even if it is something to do with the built-in Emacs shell, we can still try to diagnose it here.  Another thing you could check is the output of `command -v curl` in both environments, as it's possible you might be running different versions of curl between the two?

**Comment by riscy** [comment] 2020-08-01 23:39
I'll close this for now, but feel free to reopen if you find out that it was shx doing it. :)

**Closed by riscy** 2020-08-01 23:39 UTC
