### ISSUE TITLE
Shx disable undo typing a command?

### ISSUE THREAD

**Issue by tddsg** [riscy/shx-for-emacs#4] opened 2017-07-14 00:35 UTC
Hi,

I notice that after installing the `shx` package, I could not undo typing the current command. For example, in `shell` mode when typing `ls *.txt`, if I delete the text `*.txt`, I cannot undo it by `undo` (`C-/`). There is a message informs that "No undo information in this buffer"

I'd like to double check with you is this caused by `shx`?

Thank you!

**Comment by riscy** [comment] 2017-07-14 03:18
This is definitely caused by `shx`.

I've thought about it and decided I should have `shx` *not* disable undo in the next release, and rather make it a customization option.  The benefit is it makes the shell a little faster, but I think it's too surprising.

Thanks for pointing this out!

**Comment by riscy** [comment] 2017-07-14 17:47
Should be fixed in the latest release.  Thanks again. :)

**Closed by riscy** 2017-07-14 17:47 UTC

**Comment by tddsg** [comment] 2017-07-15 06:39
Thank you for the update! (y)
